# Portfolio Optimization _ Monte Carlo Simulations

## IMPORT DATASETS AND LIBRARIES

In [ ]:
# Mount the drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from copy import copy
from scipy import stats
import plotly.express as px
import plotly.figure_factory as ff
import plotly.graph_objects as go

In [ ]:
# Ignore harmless warnings
import warnings
warnings.filterwarnings("ignore")

In [ ]:
from tqdm.notebook import tqdm

In [ ]:
# Read the stock data csv file, here's the list of the stocks considered:

# AAPL = Apple Stock 
# BA = Boeing 
# T = AT&T
# MGM = MGM Resorts International (Hotel Industry)
# AMZN = Amazon
# IBM = IBM
# TSLA = Tesla Motors
# GOOG = Google 
# sp500 = US Stock Market (S&P 500 is a stock market index that measures the stock performance of 500 large companies listed on U.S. stock exchange)
# Check the list of S&P 500 companies here: https://en.wikipedia.org/wiki/List_of_S%26P_500_companies

stocks_df = pd.read_csv('/content/drive/MyDrive/my files/Financial Analysis/stock.csv')
stocks_df

Date        AAPL          BA  ...         TSLA         GOOG        sp500
0     2012-01-12   60.198570   75.510002  ...    28.250000   313.644379  1295.500000
1     2012-01-13   59.972858   74.599998  ...    22.790001   311.328064  1289.089966
2     2012-01-17   60.671429   75.239998  ...    26.600000   313.116364  1293.670044
3     2012-01-18   61.301430   75.059998  ...    26.809999   315.273285  1308.040039
4     2012-01-19   61.107143   75.559998  ...    26.760000   318.590851  1314.500000
...          ...         ...         ...  ...          ...          ...          ...
2154  2020-08-05  440.250000  174.279999  ...  1485.020020  1473.609985  3327.770020
2155  2020-08-06  455.609985  172.199997  ...  1489.579956  1500.099976  3349.159912
2156  2020-08-07  444.450012  170.020004  ...  1452.709961  1494.489990  3351.280029
2157  2020-08-10  450.910004  179.410004  ...  1418.569946  1496.099976  3360.469971
2158  2020-08-11  437.500000  180.130005  ...  1374.390015  1480.319946  3333.689941

[2159 rows x 10 columns]

In [ ]:
# Sort the stock data by date
stocks_df = stocks_df.sort_values(by = ['Date'])
stocks_df

Date        AAPL          BA  ...         TSLA         GOOG        sp500
0     2012-01-12   60.198570   75.510002  ...    28.250000   313.644379  1295.500000
1     2012-01-13   59.972858   74.599998  ...    22.790001   311.328064  1289.089966
2     2012-01-17   60.671429   75.239998  ...    26.600000   313.116364  1293.670044
3     2012-01-18   61.301430   75.059998  ...    26.809999   315.273285  1308.040039
4     2012-01-19   61.107143   75.559998  ...    26.760000   318.590851  1314.500000
...          ...         ...         ...  ...          ...          ...          ...
2154  2020-08-05  440.250000  174.279999  ...  1485.020020  1473.609985  3327.770020
2155  2020-08-06  455.609985  172.199997  ...  1489.579956  1500.099976  3349.159912
2156  2020-08-07  444.450012  170.020004  ...  1452.709961  1494.489990  3351.280029
2157  2020-08-10  450.910004  179.410004  ...  1418.569946  1496.099976  3360.469971
2158  2020-08-11  437.500000  180.130005  ...  1374.390015  1480.319946  3333.689941

[2159 rows x 10 columns]

In [ ]:
# Print out the number of stocks
print('Total Number of stocks : {}'.format(len(stocks_df.columns[1:])))

Total Number of stocks : 9


In [ ]:
# Print the name of stocks
print('Stocks under consideration are:')

for i in stocks_df.columns[1:]:
  print(i)

Stocks under consideration are:
AAPL
BA
T
MGM
AMZN
IBM
TSLA
GOOG
sp500


In [ ]:
stocks_df.describe()

AAPL           BA  ...         GOOG        sp500
count  2159.000000  2159.000000  ...  2159.000000  2159.000000
mean    140.819823   189.942700  ...   783.712512  2218.749554
std      70.827601   103.678586  ...   334.448057   537.321727
min      55.790001    67.239998  ...   278.481171  1278.040039
25%      89.165714   124.015000  ...   527.214416  1847.984985
50%     116.599998   142.419998  ...   737.599976  2106.629883
75%     175.019997   297.044998  ...  1079.744995  2705.810059
max     455.609985   440.619995  ...  1568.489990  3386.149902

[8 rows x 9 columns]

In [ ]:
# Check if data contains any null values
stocks_df.isnull().sum()

Date     0
AAPL     0
BA       0
T        0
MGM      0
AMZN     0
IBM      0
TSLA     0
GOOG     0
sp500    0
dtype: int64

In [ ]:
# Getting dataframe info
stocks_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2159 entries, 0 to 2158
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    2159 non-null   object 
 1   AAPL    2159 non-null   float64
 2   BA      2159 non-null   float64
 3   T       2159 non-null   float64
 4   MGM     2159 non-null   float64
 5   AMZN    2159 non-null   float64
 6   IBM     2159 non-null   float64
 7   TSLA    2159 non-null   float64
 8   GOOG    2159 non-null   float64
 9   sp500   2159 non-null   float64
dtypes: float64(9), object(1)
memory usage: 185.5+ KB


In [ ]:
# Plot interactive chart
interactive_plot(stocks_df, 'Prices')

***If you want to create a portfolio to maximize cummulative returns with no regards of risk, what would the portfolio weights be based on the graph above?***

no, by the normalized graph. weights would be [1, 0, 0, 0, 0, 0, 0, 0, 0] 

***What would the cummulative return be?***

Cummulative return ~= 50x

In [ ]:
# Plot normalized interactive chart
interactive_plot(normalize(stocks_df), 'Normalized Prices')

## DEFINE PORTFOLIO ALLOCATION FUNCTION

In [ ]:
# Let's create random portfolio weights
# Portfolio weights must sum to 1 

# Set random seed
# np.random.seed(101)

# Create random weights for the stocks and normalize them
weights = np.array(np.random.random(9))

# Ensure that the sum of all weights are = 1
weights = weights / np.sum(weights) 
print(weights)


[0.09515328 0.17445787 0.13694668 0.0670513  0.01570873 0.08254487
 0.21430404 0.04869263 0.16514061]


In [ ]:
# Lets assume we have $1,000,000 to be invested and we will allocate this fund based on the weights of the stocks
# We will create a function that takes in the stock prices along with the weights and retun:
# (1) Daily value of each individual securuty in $ over the specified time period
# (2) Overall daily worth of the entire portfolio 
# (3) Daily return 

def portfolio_allocation(df, weights):

  df_portfolio = df.copy()
  
  # Normalize the stock avalues 
  df_portfolio = normalize(df_portfolio)
  
  for counter, stock in enumerate(df_portfolio.columns[1:]):
    df_portfolio[stock] = df_portfolio[stock] * weights[counter]
    df_portfolio[stock] = df_portfolio[stock] * 1000000

  df_portfolio['portfolio daily worth in $'] = df_portfolio[df_portfolio != 'Date'].sum(axis = 1)
  
  df_portfolio['portfolio daily % return'] = 0.0000

  for i in range(1, len(stocks_df)):
    
    # Calculate the percentage of change from the previous day
    df_portfolio['portfolio daily % return'][i] = ( (df_portfolio['portfolio daily worth in $'][i] - df_portfolio['portfolio daily worth in $'][i-1]) / df_portfolio['portfolio daily worth in $'][i-1]) * 100 
  
  # set the value of first row to zero, as previous value is not available
  df_portfolio['portfolio daily % return'][0] = 0
  return df_portfolio

In [ ]:
# Get the portfolio allocation for the randomly selected weights
df_portfolio = portfolio_allocation(stocks_df, weights)
df_portfolio  

Date  ...  portfolio daily % return
0     2012-01-12  ...                  0.000000
1     2012-01-13  ...                 -4.447981
2     2012-01-17  ...                  3.483534
3     2012-01-18  ...                  0.863722
4     2012-01-19  ...                  0.280680
...          ...  ...                       ...
2154  2020-08-05  ...                  0.131375
2155  2020-08-06  ...                  0.534025
2156  2020-08-07  ...                 -2.230213
2157  2020-08-10  ...                 -1.580497
2158  2020-08-11  ...                 -2.796165

[2159 rows x 12 columns]

In [ ]:
# Daily return of every stock in the portfolio (Note that we dropped the date, portfolio daily worth and daily % returns) 
# Note that we used pct.change() which calculates the percentage change between the current and a prior element.
# Note that 1 indicates one time period 

df_portfolio_daily_return = df_portfolio.drop(columns = ['Date', 'portfolio daily worth in $', 'portfolio daily % return'])
df_portfolio_daily_return = df_portfolio_daily_return.pct_change(1) 
df_portfolio_daily_return

AAPL        BA         T  ...      TSLA      GOOG     sp500
0          NaN       NaN       NaN  ...       NaN       NaN       NaN
1    -0.003749 -0.012051 -0.001660  ... -0.193274 -0.007385 -0.004948
2     0.011648  0.008579  0.005986  ...  0.167179  0.005744  0.003553
3     0.010384 -0.002392  0.002645  ...  0.007895  0.006889  0.011108
4    -0.003169  0.006661  0.002967  ... -0.001865  0.010523  0.004939
...        ...       ...       ...  ...       ...       ...       ...
2154  0.003625  0.055794 -0.005332  ... -0.001332  0.005898  0.006430
2155  0.034889 -0.011935 -0.000335  ...  0.003071  0.017976  0.006428
2156 -0.024495 -0.012660  0.006032  ... -0.024752 -0.003740  0.000633
2157  0.014535  0.055229  0.005996  ... -0.023501  0.001077  0.002742
2158 -0.029740  0.004013  0.000000  ... -0.031144 -0.010547 -0.007969

[2159 rows x 9 columns]

In [ ]:
# Average/Std/min/max return for each individual stock in the portfolio
# MGM made 33% daily return in one day!!
df_portfolio_daily_return.describe()

AAPL           BA  ...         GOOG        sp500
count  2158.000000  2158.000000  ...  2158.000000  2158.000000
mean      0.001077     0.000659  ...     0.000844     0.000493
std       0.017762     0.022603  ...     0.015859     0.010491
min      -0.128647    -0.238484  ...    -0.111008    -0.119841
25%      -0.006925    -0.007842  ...    -0.006147    -0.003189
50%       0.000833     0.000782  ...     0.000612     0.000594
75%       0.010019     0.009467  ...     0.008610     0.005021
max       0.119808     0.243186  ...     0.160524     0.093828

[8 rows x 9 columns]

In [ ]:
# Obtain the expected portfolio return by multiplying the weights * average return of each security
portfolio_expected_return = np.sum(df_portfolio_daily_return.mean() * weights * 252)
portfolio_expected_return

0.23298778950949933

In [ ]:
# Calculate the porfolio Covariance which is the first step in calculating the portfolio volatility 
# Covariance determines the relationship between two stock prices movement.
# If two stocks have positive covariance, that means that their price moves together
# Covariance is crucial for asset pairing by selecting stocks with negative covariance values in order to reduce risk or volatility 
covariance = df_portfolio_daily_return.cov() * 252 # 252 to obtain the annualized covariance values
covariance

AAPL        BA         T  ...      TSLA      GOOG     sp500
AAPL   0.079501  0.038976  0.019331  ...  0.044308  0.036140  0.030866
BA     0.038976  0.128750  0.028941  ...  0.049040  0.035054  0.038353
T      0.019331  0.028941  0.040335  ...  0.016682  0.017883  0.020652
MGM    0.047229  0.086728  0.029794  ...  0.074076  0.048215  0.045861
AMZN   0.035407  0.029377  0.014333  ...  0.051694  0.044333  0.027505
IBM    0.027839  0.039074  0.022096  ...  0.030394  0.026246  0.026637
TSLA   0.044308  0.049040  0.016682  ...  0.296617  0.044261  0.035184
GOOG   0.036140  0.035054  0.017883  ...  0.044261  0.063382  0.028702
sp500  0.030866  0.038353  0.020652  ...  0.035184  0.028702  0.027735

[9 rows x 9 columns]

In [ ]:
# Calculate the Portfolio variance
variance = np.dot(weights.T, np.dot(covariance, weights))
variance

0.05217908900244294

In [ ]:
# Expected volatility in % format
print('Potfolio Variance = {:.2f}%'.format(variance * 100))

Potfolio Variance = 5.22%


In [ ]:
# Calculate the portfolio standard deviation (Expected volatility or dispertion away from the mean) which is the squareroot of its variance 
standard_deviation = np.sqrt(np.dot(weights.T, np.dot(covariance, weights)))
standard_deviation

0.22842742611701192

In [ ]:
# Expected volatility in % format
print('Potfolio standard deviation (volatility)) = {:.2f}%'.format(standard_deviation * 100))

Potfolio standard deviation (volatility)) = 22.84%


In [ ]:
# Portfolio sharpe ratio
# Standard deviation is the expected volatility
expected_volatility = standard_deviation

sharpe_ratio = portfolio_expected_return/expected_volatility 
sharpe_ratio

1.0199641674820228

## CALCULATE PORTFOLIO STATISTICAL ANALYSIS KEY METRICS (FUNCTION)

In [ ]:
# Let's put all of these statistical measures in one function!
def portfolio_statistical_analysis(weights):

  # Get the portfolio allocation for the specified weights (sent as arguments)
  df_portfolio = portfolio_allocation(stocks_df, weights)
  
  # Cummulative return of the portfolio (Note that we now look for the last net worth of the portfolio compared to it's start value)
  cummulative_return = ((df_portfolio['portfolio daily worth in $'][-1:] - df_portfolio['portfolio daily worth in $'][0])/ df_portfolio['portfolio daily worth in $'][0]) * 100
  
  # Daily change of every stock in the portfolio (Note that we dropped the date, portfolio daily worth and daily % returns) 
  df_portfolio_daily_return = df_portfolio.drop(columns = ['Date', 'portfolio daily worth in $', 'portfolio daily % return'])
  df_portfolio_daily_return = df_portfolio_daily_return.pct_change(1) 
  
  # Portfolio Expected Annual Return 
  expected_portfolio_return = np.sum(df_portfolio_daily_return.mean() * weights * 252)
  
  # Portfolio Expected Volatility
  covariance = df_portfolio_daily_return.cov() * 252 
  expected_volatility = np.sqrt(np.dot(weights.T, np.dot(covariance, weights)))
  
  # Portfolio sharpe ratio
  sharpe_ratio = expected_portfolio_return/expected_volatility 

  return cummulative_return.values[0], expected_portfolio_return, expected_volatility, sharpe_ratio
  

***Assume that we will allocate equal amount of money to all stocks (equal weights), what would the Sharpe ratio be? volatility? and Expected return?***



In [ ]:
# Ensure that the sum of all weights are = 1
weights = [1/9,1/9,1/9,1/9,1/9,1/9,1/9,1/9,1/9]
weights = np.array(weights)
print(weights)

[0.11111111 0.11111111 0.11111111 0.11111111 0.11111111 0.11111111
 0.11111111 0.11111111 0.11111111]


In [ ]:
statistical_metrics = portfolio_statistical_analysis(weights);
statistical_metrics # Tuple with all statistical measures

(862.0559887886882,
 0.21389589061774253,
 0.20998307961973936,
 1.0186339347203066)

In [ ]:
# Print out the statistical metrics
print('Portfolio Cummulative Return = {:.2f}%'.format(portfolio_statistical_analysis(weights)[0]))
print('Expected portfolio returns = {:.2f}%'.format(portfolio_statistical_analysis(weights)[1] * 100))
print('Expected volatility = {:.2f}%'.format(portfolio_statistical_analysis(weights)[2] * 100))
print('Sharpe Ratio = {:.2f}'.format(portfolio_statistical_analysis(weights)[3]))

Portfolio Cummulative Return = 862.06%
Expected portfolio returns = 21.39%
Expected volatility = 21.00%
Sharpe Ratio = 1.02


## PORTFOLIO OPTIMIZATION WITH RANDOM ALLOCATION USING MONTE CARLO SIMULATIONS

In [ ]:
# Create random weights and analayze the portfolio to find the optimal weight allocation

number_of_trials = 2000 # you will need more 

# Placeholder to store the weights
possible_weights_runs = np.zeros((number_of_trials, 9))

# Placeholder to store the sharpe ratios
sharpe_ratio_runs = np.zeros(number_of_trials)

# Placeholder to store the returns
expected_portfolio_returns_runs = np.zeros(number_of_trials)

# Placeholder to store the volatility
volatility_runs = np.zeros(number_of_trials)

# Placeholder to store the cummulative returns
cummulative_returns_runs = np.zeros(number_of_trials)

for i in tqdm(range(number_of_trials)):
    # Random Weights
    weights = np.array(np.random.random(9))
    weights = weights / np.sum(weights)
    
    # Store the weights
    possible_weights_runs[i,:] = weights
    
    # Store the sharpe ratio, return and volatility
    cummulative_returns_runs[i], expected_portfolio_returns_runs[i], volatility_runs[i], sharpe_ratio_runs[i]  = portfolio_statistical_analysis(weights)

  0%|          | 0/2000 [00:00<?, ?it/s]

In [ ]:
# A list of all possible Sharpe ratios (2000 runs)
print(sharpe_ratio_runs.shape)
print(sharpe_ratio_runs)

(2000,)
[0.90527768 1.08022375 1.10468422 ... 0.89992626 0.87296182 0.85810093]


In [ ]:
# A list of all possible portfolio expected returns (2000 runs)
expected_portfolio_returns_runs

array([0.19586622, 0.22372909, 0.24802071, ..., 0.1741697 , 0.20766033,
       0.18059235])

In [ ]:
# A list of all cummulative returns (2000 runs)
cummulative_returns_runs

array([ 578.59394341, 1165.63675286, 1210.61294333, ...,  471.22191809,
       1113.43386471,  547.17037742])

In [ ]:
# A list of all possible portfolio weights
possible_weights_runs

array([[0.05280295, 0.16079181, 0.13460842, ..., 0.03191986, 0.18823879,
        0.00697639],
       [0.00753845, 0.05130938, 0.14959863, ..., 0.16859187, 0.03112167,
        0.18796741],
       [0.1590135 , 0.01522135, 0.19467688, ..., 0.1846493 , 0.08148094,
        0.02651227],
       ...,
       [0.15588817, 0.0901497 , 0.10508645, ..., 0.03405768, 0.04706215,
        0.325633  ],
       [0.00263031, 0.11406997, 0.09493812, ..., 0.21303071, 0.09484342,
        0.07818222],
       [0.04583573, 0.04249885, 0.05831061, ..., 0.02488889, 0.07083475,
        0.20367855]])

***What is the best portfolio that maximizes Sharpe ratio?***

***What are the weights corresponding to this maximum Sharpe Ratio?***

In [ ]:
# Return the index of the maximum Sharpe ratio (Best run that maximizes return and reduces risk)
sharpe_ratio_runs.argmax()

303

In [ ]:
# Return the maximum Sharpe ratio
sharpe_ratio_runs.max()

1.323746657173723

In [ ]:
# Weights that corresponds to the maximum sharpe ratio (Golden set of weights!!)
possible_weights_runs[sharpe_ratio_runs.argmax(),:]

array([0.20481548, 0.033401  , 0.00030378, 0.02022166, 0.23875935,
       0.0993115 , 0.17593835, 0.11254007, 0.11470881])

In [ ]:
# Return the cummulative return, sharpe ratio, volatility corresponding to the best weights allocation (maximum Sharpe ratio)
optimal_cummulative_return, optimal_portfolio_return, optimal_volatility, optimal_sharpe_ratio = portfolio_statistical_analysis(possible_weights_runs[sharpe_ratio_runs.argmax(), :])

In [ ]:
print('Best Portfolio metrics based on {} Monte Carlo Simulation runs:'.format(number_of_trials))
print('  - Optimal Cummulative return of the portfolio = {}%'.format(optimal_cummulative_return))
print('  - Portfolio Expected return per year = {:.02f}%'.format(optimal_portfolio_return * 100))
print('  - Volatility of the portfolio = {:.02f}%'.format(optimal_volatility * 100))
print('  - Sharpe ratio of the portfolio = {}'.format(optimal_sharpe_ratio))

Best Portfolio metrics based on 2000 Monte Carlo Simulation runs:
  - Optimal Cummulative return of the portfolio = 1424.0834680292692%
  - Portfolio Expected return per year = 29.79%
  - Volatility of the portfolio = 22.50%
  - Sharpe ratio of the portfolio = 1.323746657173723


## PLOT THE OUTCOME OF ALL SIMULATION SCENARIOS

In [ ]:
# Create a DataFrame with all volatilties, portfolio returns, and sharpe ratios
df_optimize = pd.DataFrame({'Volatility': volatility_runs.tolist(), 'Portfolio_Return': expected_portfolio_returns_runs.tolist(), 'Sharpe_Ratio': sharpe_ratio_runs.tolist() })
df_optimize

Volatility  Portfolio_Return  Sharpe_Ratio
0       0.216360          0.195866      0.905278
1       0.207114          0.223729      1.080224
2       0.224517          0.248021      1.104684
3       0.191230          0.188356      0.984972
4       0.204820          0.185210      0.904255
...          ...               ...           ...
1995    0.234326          0.228159      0.973681
1996    0.203588          0.210169      1.032328
1997    0.193538          0.174170      0.899926
1998    0.237880          0.207660      0.872962
1999    0.210456          0.180592      0.858101

[2000 rows x 3 columns]

In [ ]:
# Plot interactive plot for volatility
fig = px.line(df_optimize, y = 'Volatility')
fig.show()

In [ ]:
# Plot interactive plot for Portfolio Return
fig = px.line(df_optimize, y = 'Portfolio_Return')
fig.update_traces(line_color='red')
fig.show()

In [ ]:
# Plot interactive plot for Portfolio Return
fig = px.line(df_optimize, y = 'Sharpe_Ratio')
fig.update_traces(line_color='purple')
fig.show()

In [ ]:
# Plot all the obtained volatility vs. returns 
# Highlight the volatility and return corresponding to highest sharpe ratio
fig = px.scatter(df_optimize, x = 'Volatility', y = 'Portfolio_Return', color = 'Sharpe_Ratio', size = 'Sharpe_Ratio', hover_data = ['Sharpe_Ratio'] )

# Let's add this line to highlight the point with the highest Sharpe Ratio
fig.add_trace(go.Scatter(x = [optimal_volatility], y = [optimal_portfolio_return], mode = 'markers', name = 'Optimal Point', marker = dict(size=[50], color = 'yellow')))

fig.update_layout(coloraxis_colorbar = dict(
    title = "Sharpe Ratio",
    thicknessmode = "pixels", thickness = 25,
    lenmode = "pixels",
    yanchor = "middle", y = 0.4,
    dtick = 5
))

fig.show()

## PORFOLIO OPTIMIZATION USING OPTIMIZERS

In [ ]:
# SciPy is an open-source ecosystems for mathematical calculations 
# We will minimize the cost function using Sequential Least Squares Programming (SLSQP)
# Check this out for more details: https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize

from scipy.optimize import minimize

# Since optimization works as a minimizing function, we take negative of sharpe ratio and then try minimize it.

# Define a function that calculates the negative Sharpe ratio
def calculate_negative_sharpe_func(weights):
  cum_return, exp_portfolio_return, volatility, sharpe_ratio = portfolio_statistical_analysis(weights)
  return sharpe_ratio * -1

# Function to define optimization constraints (make sure sum of all weights add to 1)
def optimization_constraints_func(weights):
  return np.sum(weights) - 1

# Function to obtain the "volatility" for a given set of portfolio weights
def calculate_volatility_func(weights):
  cum_return, exp_portfolio_return, volatility, sharpe_ratio = portfolio_statistical_analysis(weights)
  return volatility

# Function to get the return for a particular weight
def calculate_return_func(weights):
  cum_return, exp_portfolio_return, volatility, sharpe_ratio = portfolio_statistical_analysis(weights)
  return exp_portfolio_return

In [ ]:
# Constraints to pass to the optimizer
optimization_constraint = ({'type':'eq','fun': optimization_constraints_func})

# Lower and upper bounds for weights you can change it
bounds = ((0, 1), (0, 1), (0, 1), (0, 1),(0, 1), (0, 1), (0, 1), (0, 1),(0,1))

# Initial weight assumption
initialization = [0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25]

In [ ]:
# Optimization Function
# Optimization Algorithms is SLSQP stands for Sequential Least Squares Programming (SLSQP)   
optimization_results = minimize(calculate_negative_sharpe_func, initialization, method = 'SLSQP', bounds = bounds, constraints = optimization_constraint)

In [ ]:
optimized_weights = optimization_results.x
optimized_weights

array([2.58475028e-01, 4.89373446e-17, 5.47513919e-17, 5.60739097e-17,
       5.04003404e-01, 1.31670373e-16, 2.37521567e-01, 3.06943216e-17,
       2.91071303e-17])

In [ ]:
# Analyze the portfolio based on the obtained weights
cummulative_return_SLSQP, portfolio_return_value_SLSQP, vol_value_SLSQP, sharpe_ratio_SLSQP = portfolio_statistical_analysis(optimized_weights)

In [ ]:
print('Best Portfolio metrics based on SLSQP optimizer:')
print('  - Optimal Cummulative return of the portfolio = {}%'.format(cummulative_return_SLSQP))
print('  - Portfolio Expected return per year = {:.02f}%'.format(portfolio_return_value_SLSQP * 100))
print('  - Volatility of the portfolio = {:.02f}%'.format(vol_value_SLSQP * 100))
print('  - Sharpe ratio of the portfolio = {}'.format(sharpe_ratio_SLSQP))

Best Portfolio metrics based on SLSQP optimizer:
  - Optimal Cummulative return of the portfolio = 2125.9640944265357%
  - Portfolio Expected return per year = 40.50%
  - Volatility of the portfolio = 27.00%
  - Sharpe ratio of the portfolio = 1.4999984047118262


## PLOTTING MARKOWITZ EFFICIENT FRONTIER

In [ ]:
# The efficient frontier represents a set of portfolios that produces the highest return for any risk level 
# the efficient fronitier represents the portfolio with the least amount of risk (volatility)(x-axis) for any given expected return (y-axis)
# The returns range from 0 to 0.35 so we will obtain x number of y-positions (x = 50) to calculate the optimal volatility for that return
frontier_y = np.linspace(0, 0.35, 50)

In [ ]:
frontier_volatility = []

# Calculate the optimal volatility for each return
for possible_return in frontier_y:

    # Conditions for optimization
    condition = ({'type':'eq', 'fun': optimization_constraints_func},
                 {'type':'eq', 'fun': lambda w: calculate_return_func(w) - possible_return})
    
    result = minimize(calculate_volatility_func, initialization, method = 'SLSQP', bounds = bounds, constraints = condition)
    
    frontier_volatility.append(result['fun'])

In [ ]:
# Plot the efficient frontier
fig = px.scatter(df_optimize, x = 'Volatility', y = 'Portfolio_Return', color = 'Sharpe_Ratio' )
fig.add_trace(go.Scatter(x = frontier_volatility, y = frontier_y.tolist(), name = 'Frontier'))
# fig.add_trace(go.Scatter(x = [vol_value], y = [portfolio_return_value], mode = 'markers', name = 'Optimal Point', marker_color = 'black'))
fig.show()